version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "twitterDemoTs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1goe0sadhjzcs"
s3_prefix = "twitterDemoTs"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
